custom.datasource.url=jdbc:mysql://localhost:3306/purchases?useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false

custom.datasource.username=root
custom.datasource.password=1q2w3e4r